# Generated by Django 3.2.7 on 2021-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('number', models.CharField(blank=True, max_length=14, null=True, verbose_name='Телефон')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
